version: "3.0"

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .dev.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 80:3000
      - 9229:9229
    command: npm run start:dev
    restart: always
    networks:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .dev.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "${COMPOSE_PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${COMPOSE_PGADMIN_DEFAULT_PASSWORD}"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  pgdata: