version: "3.8"

services:
  storage:
    container_name: storage
    build:
      context: .
    env_file:
      - ./.dev.env
    volumes:
      - ./src:/usr/app/storage_node/src
      - ./storage:/usr/app/storage_node/storage
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    restart: always
    networks:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:12-alpine
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DATABASE}"
    ports:
      - 5434:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.14
    environment:
      PGADMIN_DEFAULT_EMAIL: "${COMPOSE_PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${COMPOSE_PGADMIN_DEFAULT_PASSWORD}"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  pgdata:
  pgadmin: